import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { UserPlus, CheckCircle, Search, Stethoscope, Clock, Printer } from "lucide-react";

// PLACEHOLDER: Fetch existing patients from GET /api/patients/search?q=
// Used to check if walk-in patient is already registered in the system

const SERVICES = [
  "General Consultation",
  "Physical Check-up",
  "Pediatrics",
  "Vaccination / Immunization",
  "Eye Consultation",
  "Prescription Renewal",
  "Follow-up Check",
];

// PLACEHOLDER: Generated by server — POST /api/queue/walkin returns new token
const MOCK_GENERATED_TOKEN = "A-063";

export default function WalkInRegistration() {
  const [step, setStep] = useState<"search" | "form" | "done">("search");
  const [searchQuery, setSearchQuery] = useState("");
  const [isNewPatient, setIsNewPatient] = useState<boolean | null>(null);
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({
    firstName: "",
    lastName: "",
    phone: "",
    age: "",
    gender: "Male",
    service: "",
    chiefComplaint: "",
    severity: "3",
    isUrgent: false,
  });

  // PLACEHOLDER: API search GET /api/patients/search?q={searchQuery}
  const handleSearch = async () => {
    setLoading(true);
    await new Promise((r) => setTimeout(r, 800));
    setLoading(false);
    // Simulate no existing patient found
    setIsNewPatient(true);
    setStep("form");
  };

  // PLACEHOLDER: POST /api/queue/walkin with patient data
  // If new patient: also creates patient record in database
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    await new Promise((r) => setTimeout(r, 1200));
    setLoading(false);
    setStep("done");
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 max-w-2xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-extrabold text-gray-900 mb-1">Walk-in Registration</h1>
        <p className="text-gray-500 text-sm">Register a walk-in patient and add them to today's queue.</p>
      </div>

      <AnimatePresence mode="wait">
        {/* ── SEARCH STEP ── */}
        {step === "search" && (
          <motion.div key="search" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-6 mb-5">
              <h3 className="font-bold text-gray-900 mb-2">Search Existing Patient</h3>
              <p className="text-sm text-gray-500 mb-5">
                {/* PLACEHOLDER: Search in patient database by name, phone, or patient ID */}
                Search to check if the patient is already registered in the system.
              </p>
              <div className="relative mb-4">
                <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search by name, phone, or Patient ID..."
                  className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                  onKeyDown={(e) => e.key === "Enter" && handleSearch()}
                />
              </div>
              <div className="flex gap-3">
                <button
                  onClick={handleSearch}
                  disabled={loading}
                  className="flex-1 bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold py-3 rounded-2xl shadow-md flex items-center justify-center gap-2 disabled:opacity-60"
                >
                  {loading ? (
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <Search className="w-4 h-4" />
                  )}
                  Search Patient
                </button>
                <button
                  onClick={() => { setIsNewPatient(true); setStep("form"); }}
                  className="flex-1 border-2 border-green-200 text-green-700 font-semibold py-3 rounded-2xl hover:bg-green-50"
                >
                  New Patient →
                </button>
              </div>
            </div>

            {/* PLACEHOLDER: Recent walk-ins from GET /api/staff/walkins/recent */}
            <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-5">
              <h4 className="font-bold text-gray-700 text-sm mb-3">Recent Walk-ins Today</h4>
              {[
                { token: "A-044", name: "Carlos Mendoza", service: "General Consultation", time: "8:32 AM" },
                { token: "A-051", name: "Roberto Garcia", service: "Vaccination", time: "9:42 AM" },
                { token: "A-056", name: "Celine Lopez", service: "Prescription Renewal", time: "10:05 AM" },
              ].map((w, i) => (
                <div key={i} className="flex items-center gap-3 py-2.5 border-b border-gray-50 last:border-0">
                  <div className="w-10 h-10 bg-green-50 text-green-700 font-black text-sm rounded-xl flex items-center justify-center">
                    {w.token}
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-semibold text-gray-800">{w.name}</p>
                    <p className="text-xs text-gray-400">{w.service}</p>
                  </div>
                  <p className="text-xs text-gray-400 flex-shrink-0">{w.time}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* ── FORM STEP ── */}
        {step === "form" && (
          <motion.div key="form" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            {isNewPatient && (
              <div className="bg-blue-50 border border-blue-100 rounded-2xl px-4 py-3 mb-5 flex items-center gap-2">
                <UserPlus className="w-4 h-4 text-blue-500" />
                <p className="text-sm text-blue-700 font-medium">
                  New patient — a basic record will be created in the system.
                </p>
              </div>
            )}

            <form onSubmit={handleSubmit}>
              <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-6 space-y-5 mb-5">
                <h3 className="font-bold text-gray-900">Patient Information</h3>

                {/* PLACEHOLDER: All fields saved to patients table in database */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">First Name *</label>
                    <input
                      required
                      value={form.firstName}
                      onChange={(e) => setForm({ ...form, firstName: e.target.value })}
                      placeholder="First name"
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">Last Name *</label>
                    <input
                      required
                      value={form.lastName}
                      onChange={(e) => setForm({ ...form, lastName: e.target.value })}
                      placeholder="Last name"
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">Phone</label>
                    <input
                      value={form.phone}
                      onChange={(e) => setForm({ ...form, phone: e.target.value })}
                      placeholder="+63 9XX..."
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">Age</label>
                    <input
                      type="number"
                      value={form.age}
                      onChange={(e) => setForm({ ...form, age: e.target.value })}
                      placeholder="Age"
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">Gender</label>
                    <select
                      value={form.gender}
                      onChange={(e) => setForm({ ...form, gender: e.target.value })}
                      className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    >
                      <option>Male</option>
                      <option>Female</option>
                    </select>
                  </div>
                </div>

                {/* Service */}
                <div>
                  <label className="block text-xs font-semibold text-gray-500 mb-1.5">Service / Reason for Visit *</label>
                  <div className="relative">
                    <Stethoscope className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                    <select
                      required
                      value={form.service}
                      onChange={(e) => setForm({ ...form, service: e.target.value })}
                      className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400"
                    >
                      <option value="">Select a service</option>
                      {SERVICES.map((s) => <option key={s}>{s}</option>)}
                    </select>
                  </div>
                </div>

                {/* Chief Complaint */}
                <div>
                  <label className="block text-xs font-semibold text-gray-500 mb-1.5">Chief Complaint</label>
                  <textarea
                    required
                    value={form.chiefComplaint}
                    onChange={(e) => setForm({ ...form, chiefComplaint: e.target.value })}
                    placeholder="Describe the patient's main concern..."
                    rows={2}
                    className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-green-400 resize-none"
                  />
                </div>

                {/* Severity & Urgent Flag */}
                <div className="flex items-center gap-4">
                  <div className="flex-1">
                    <label className="block text-xs font-semibold text-gray-500 mb-1.5">
                      Severity Level: <span className="text-green-700 font-bold">{form.severity}/10</span>
                    </label>
                    {/* PLACEHOLDER: Severity ≥ 8 triggers automatic urgent flag in AI triage */}
                    <input
                      type="range"
                      min="1"
                      max="10"
                      value={form.severity}
                      onChange={(e) => setForm({ ...form, severity: e.target.value })}
                      className="w-full accent-green-500"
                    />
                  </div>
                  <label className="flex items-center gap-2 cursor-pointer flex-shrink-0">
                    <div
                      onClick={() => setForm({ ...form, isUrgent: !form.isUrgent })}
                      className={`w-11 h-6 rounded-full transition-colors relative ${form.isUrgent ? "bg-red-500" : "bg-gray-200"}`}
                    >
                      <div className={`absolute top-1 w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${form.isUrgent ? "translate-x-6" : "translate-x-1"}`} />
                    </div>
                    <span className="text-sm font-semibold text-gray-700">
                      {/* PLACEHOLDER: Urgent flag triggers priority override in queue engine */}
                      Mark Urgent
                    </span>
                  </label>
                </div>
              </div>

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setStep("search")}
                  className="border-2 border-gray-200 text-gray-600 font-semibold px-6 py-3.5 rounded-2xl hover:bg-gray-50 text-sm"
                >
                  Back
                </button>
                <motion.button
                  whileTap={{ scale: 0.97 }}
                  type="submit"
                  disabled={loading}
                  className="flex-1 bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold py-3.5 rounded-2xl shadow-lg flex items-center justify-center gap-2 disabled:opacity-60"
                >
                  {loading ? (
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <>
                      <UserPlus className="w-5 h-5" />
                      Add to Queue
                    </>
                  )}
                </motion.button>
              </div>
            </form>
          </motion.div>
        )}

        {/* ── DONE STEP ── */}
        {step === "done" && (
          <motion.div
            key="done"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="text-center"
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: "spring", stiffness: 300, damping: 20 }}
              className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"
            >
              <CheckCircle className="w-10 h-10 text-green-500" />
            </motion.div>
            <h2 className="text-2xl font-extrabold text-gray-900 mb-1">Patient Added!</h2>
            <p className="text-gray-500 mb-6">{form.firstName} {form.lastName} has been added to today's queue.</p>

            <div className="bg-gradient-to-br from-green-600 to-emerald-700 rounded-3xl p-8 text-white shadow-xl mb-6">
              <p className="text-green-200 text-xs uppercase tracking-widest mb-2">Queue Token</p>
              {/* PLACEHOLDER: Actual token from POST /api/queue/walkin response */}
              <p className="text-8xl font-black">{MOCK_GENERATED_TOKEN}</p>
              <div className="mt-4 flex justify-center gap-8 text-sm">
                <div>
                  <p className="text-green-200 text-xs">Service</p>
                  <p className="font-semibold">{form.service || "General"}</p>
                </div>
                <div>
                  <p className="text-green-200 text-xs">Est. Wait</p>
                  {/* PLACEHOLDER: From AI estimation engine */}
                  <p className="font-semibold">~42 min</p>
                </div>
                <div>
                  <p className="text-green-200 text-xs">Position</p>
                  <p className="font-semibold">#16</p>
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => { setStep("search"); setForm({ firstName: "", lastName: "", phone: "", age: "", gender: "Male", service: "", chiefComplaint: "", severity: "3", isUrgent: false }); }}
                className="flex-1 border-2 border-green-200 text-green-700 font-semibold py-3.5 rounded-2xl hover:bg-green-50"
              >
                Register Another
              </button>
              <button className="flex-1 bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold py-3.5 rounded-2xl shadow-md flex items-center justify-center gap-2">
                {/* PLACEHOLDER: Generate printable token slip from template */}
                <Printer className="w-5 h-5" />
                Print Token
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
